### ISSUE TITLE
Unable to set up the full URL to pact-broker 

### ISSUE THREAD

**Issue by piotrsoltysiak** [pact-foundation/pact-jvm#1282]
Hi all!
I have the broker up and running on non-root path on API-gateway (`https://api.gw.url/path/to/broker`). To set it up on the contract tests, I am using the `@PactBroker` annotation:

```
@PactBroker(host = "api.gw.url/path/to/broker", scheme = "https", port = "443",
        authentication = @PactBrokerAuth(username = "username", password = "password"))
```
But with this config, error occurs:

```
java.lang.IllegalArgumentException: Invalid pact broker host specified ('api.gw.url/path/to/broker'). Please provide a valid host or specify the system property 'pactbroker.host'.
```

This error does not occur when I change the URL to connect the broker directly (without the gateway, to the root path), but for some reasons I have to use the gateway endpoint.
Is there a way to provide the full URL of the broker? 

Cheers!

**Comment by Rastafire** [comment]
Hello, I am facing the same issue than @piotrsoltysiak.

I am currently looking for a workaround, but it seems that the only thing I can do for now is to rewrite classes PactBrokerLoader and PactJUnit5VerificationProvider in my own project, since we cannot override methods of these classes...
Is there a workaround to get a "path" param in the pact-broker url, or does anybody know when it could be improved?

Many thanks!

**Comment by uglyog** [comment]
As of 4.1.19/4.2.2 you can use `@PactBroker(url = "https://api.gw.url/path/to/broker", authentication = @PactBrokerAuth(username = "username", password = "password"))`
