### ISSUE TITLE
No pacts found for provider

### ISSUE THREAD

**Issue by upanshu21** [pact-foundation/pact-jvm#1284]
I am writing consumer-driven contract test cases for an **event-based service** and using a pact broker. My consumer is able to generate the pact successfully  

```
@Tag(TestTags.MEDIUM_TESTS)
public class MessageConsumerTest {

  @ParameterizedTest
  @ConsumerMessageSource(finder = MessageFinder.class)
  void generateMessagePact(ConsumerMessage consumerMessage) {
    Assertions.assertDoesNotThrow(() -> ConsumerMessagePactGenerator.generateAndWritePact(consumerMessage));
  }
```
output:

```
Generating Pact: 

{"body":{"InitialId":"string","message":{"messageBody":"string"}}
```

I wrote the provider test for the same service:
```

@Tag(TestTags.CONTRACT_TESTS)
@PactSource(PactBrokerSourceLoader.class)
public class MessageProviderTest {

  private final MessageIndex messageIndex = new MessageIndex();

  @ParameterizedTest
  @ConsumerMessagePactSource(provider = MessageFinder.APP_NAME, config = CmdPactBrokerConfig.class)
  void messageShouldSatisfyPact(ConsumerMessagePact consumerMessagePact) throws JsonProcessingException {
    String actualMessage = messageIndex.getMessageInstanceAsString(consumerMessagePact.getMessageName());
    System.out.println("hello"+actualMessage);
    MessagePactVerifier.verifyProviderMessageMatchesPact(consumerMessagePact.getMessage(), actualMessage);
  }
```
Pact broker configurations are given in the **CmdPactBrokerConfig.class**

The test cases do not run and give the output:
```
15:21:38.037 [main] WARN com.demo.contract.message.provider.helpers.loaders.PactBrokerSourceLoader - No pacts found for provider 'demo-service' with versions 'latest, develop'
15:21:40.049 [main] WARN com.demo.contract.message.provider.helpers.arguments.ConsumerMessagePactArgumentsProvider - Unable parse pact: au.com.dius.pact.model.RequestResponsePact cannot be cast to au.com.dius.pact.model.v3.messaging.MessagePact
```

New to contract tests so need guidance on this. Any idea what could be wrong? Any example I can refer to for writing contract tests for event-based service.

**Comment by mefellows** [comment]
Looks like at least two issues:

1. The version `'latest, develop'` looks like it's not being passed as an array, but a string with commas in it. It may be an artifact of the way the logging happens, but worth double checking (because I assume you are trying to find pacts tagged `latest` and `develop`
2. Don't use `latest` as a tag (see the tagging documentation at docs.pact.io)
3. This error `Unable parse pact: au.com.dius.pact.model.RequestResponsePact cannot be cast to au.com.dius.pact.model.v3.messaging.MessagePact` suggests that the pact that was found, was not a message pact but contained the standard HTTP / REST based pacts. See https://github.com/pact-foundation/pact-specification/issues/79 for more on this. The current workaround is to have a different provider name for messages and http ones

**Comment by uglyog** [comment]
As @mefellows mentioned, `'latest, develop'` are tags, not versions. Whatever is implementing `@ConsumerMessagePactSource` needs to set the correct fields.

In your consumer test, `ConsumerMessagePactGenerator.generateAndWritePact` is generating the wrong type of Pact file.

These are not Pact-JVM classes, could you raise this issue with the project that provides those?

**Comment by upanshu21** [comment]
Yup. Actually the provider had a wrapper on top of the pact-jvm. thanks for the help closing this now.
