### ISSUE TITLE
How to configure the allowUnexpectedKeys property

### ISSUE THREAD

**Issue by ewebprojects** [pact-foundation/pact-jvm#1295]
[According to the documentation](https://docs.pact.io/implementation_guides/jvm/matching/#matching-bodies) it is possible to configure pact-jvm to ignore unexpected keys in the json body response.

```If we allow unexpected keys, and the number of expected keys is greater than the actual keys, they don't match.```

How do we do that ? There is a property allowsUnexpecteKeys in RequestMatching.kt, but I couldn't find any actual code example showing how to set that property in the tests. Any example would be much appreciated... thanks.

**Comment by BondarenkoIlya** [comment]
I have the same question. 
As far as I understand that flag could help me to check that response body(json) of my controller is equals (and don't contain any additional keys) to the response body declared in pact json itself.
I'm using JUnit5 so tried to put it into TestTemplate method and don't see any changes (for both 'true' and 'false' options) 
`@TestTemplate
        @ExtendWith(PactVerificationInvocationContextProvider.class)
        void pactVerificationTestTemplate(PactVerificationContext context) {
            context.verifyInteraction();
            RequestMatching.allowUnexpectedKeys_$eq(false);
        }`
Maybe I use it in wrong way or my expectations are wrong.

**Comment by uglyog** [comment]
`allowUnexpectedKeys` is automatically set based on whether it is matching a request body or response body. Request bodies are generally strict because in the consumer tests it should be sending exactly what is expected, so `allowUnexpectedKeys = false`. Response bodies are matched during the provider verification, so the then `allowUnexpectedKeys = true`.

Do you require the body matching to not allow extra values during the provider verification?

**Comment by uglyog** [comment]
@BondarenkoIlya that won't work, because it is set in the start of the provider verification.

**Comment by ewebprojects** [comment]
@uglyog  thanks for the clarification
