### ISSUE TITLE
How to get pact file from bitbucket

### ISSUE THREAD

**Issue by rahuldeshmukh81** [pact-foundation/pact-jvm#1328]
I have separate repository for contract file where consumer commit the file. 
Can you please suggest the way to get pact file from bitbucket to provider.

**Comment by mefellows** [comment]
I answered your question here already: https://stackoverflow.com/questions/66595666/how-to-share-pact-file-in-bitbucket.

I see you've asked this question in multiple places, and have had multiple answers. I'm not sure if that's because you're not getting the answer you want, but please be mindful of the impact each time you raise a question. I'm going to close this off for now.
