### ISSUE TITLE
ProviderResponse isn't being serialized correctly

### ISSUE THREAD

**Issue by colossatr0n** [pact-foundation/pact-jvm#1329]
Never had this happen before, but the `ProviderResponse` in my provider pact test isn't serializing the object correctly. I'm not sure how or why this is happening. 

I can run my project, hit the actual endpoint, and verify that the project is serializing the data correctly. But when using the exact same resource class in my provider pact test, the data isn't serialized correctly.

For instance, when hitting my endpoint directly, fields in the object that are `Optional<String>` get serialized as the actual string in the `Optional<String>`. So if an `Optional<String>` contains `"myString"`, then `"myString"` is how it gets serialized.

However, when testing this endpoint in the provider pact test, the `Optional<String>` is serialized as `{"empty":false,"present":true}`

This is happening with version 4.1.14, though I've tried various version from 4.1.0 to 4.1.14 and still get the same result.

**Comment by twoodhouse** [comment]
I worked with colossatr0n some on this. Here's a summary.

He's using dagger and Jersey2.

By default, Java doesn't serialize Optionals as a regular string or null as his project does. His project is reliant on the jackson jdk8module to do that. Turns out that when spinning up a jersey server to run the provider side tests, that server was not configured to use jd8module.

The solution was updating the Jersey configuration such that the same object mapper was used as is configured in the regular application startup, somewhat like the example shown here:

https://stackoverflow.com/questions/18872931/custom-objectmapper-with-jersey-2-2-and-jackson-2-1
I think this issue is closable.
