### ISSUE TITLE
publish results to broker junit5

### ISSUE THREAD

**Issue by yesid-lopez** [pact-foundation/pact-jvm#1355]
Hey there,
I was trying to publish the broker results using github actions but I don't want to do hardcode the properties in my tests, how can I do that?...

This is what I have: 
```java
     @BeforeEach
    void before(PactVerificationContext context) {
        System.setProperty("pact.verifier.publishResults", "true");
        System.setProperty("pact.provider.version", "1.0");

        MockMvcTestTarget testTarget = new MockMvcTestTarget();
        testTarget.setControllers(animalController);
        context.setTarget(testTarget);
    }
```

**Comment by uglyog** [comment]
The JVM system properties can be setup in your CI by either setting the properties on **the test JVM process** or by setting them as environment variables (which may also need to be configured to be passed on).

Both Gradle and Maven run the tests in a separate JVM process.  Most people get confused because both Gradle and Maven don't pass the environment variables or system properties defined on the command line to the test JVM. People think they can run `mvn verify -Dpact.verifier.publishResults=true`, but this will only set the property for the **Maven CLI process** but not the one running the tests.

See the docs on setting system properties for tests in Gradle (https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.Test.html) and Maven (https://maven.apache.org/surefire/maven-surefire-plugin/examples/system-properties.html).

Some stack overflow answers:
https://stackoverflow.com/questions/21406265/how-to-give-system-property-to-my-test-via-gradle-and-d
https://stackoverflow.com/questions/824019/maven-2-1-0-not-passing-on-system-properties-to-java-virtual-machine
