### ISSUE TITLE
Transport Error with grpc request.

### ISSUE THREAD

**Issue by Subhojit-Dey1234** [pact-foundation/pact-jvm#1716]
Hi, can anyone help with this error? Why is this error and the reason behind, it so that I can debug it?

```
1) Verification Failed - transport error
at au.com.dius.pact.provider.junit5.PactVerificationContext.verifyInteraction(PactVerificationContext.kt:75)
```

```
Verification Failed - gRPC error: status Operation is not implemented or not supported, message 'Method not found:'
```

**Comment by rholshausen** [comment]
`transport error` means the gRPC call was not able to be executed for some reason. It could be things like using HTTP 1 instead of HTTP 2, or using TLS when TSL is not supported or vice versa.

`gRPC error: status Operation is not implemented or not supported` means that the particular method that was being invoked is not supported or implemented by the gRPC server. `Method not found` is the error in your case.

**Comment by Subhojit-Dey1234** [comment]
I was making a silly mistake here. I was mocking the `grpc` service which was stopping the `server` from starting itself.
