### ISSUE TITLE
how do i specify optional elements in Pact Fragment

### ISSUE THREAD

**Issue by sanketi** [pact-foundation/pact-jvm#311]
Is there a way to specify optional elements in a PactDslJsonBody? I want to specify a single PactFragment and write multiple tests against it - some that will specify these optional elements and some wont. 
How could I achieve this?

Right now I get this error - 
au.com.dius.pact.consumer.PactMismatchException: Pact verification failed for the following reasons:
    BodyMismatch - Expected a Map with 4 elements but received 3 elements

TIA!

**Comment by uglyog** [comment]
Leave the optional elements out of the interactions. The pact fragment defines the contract, and should only include things that must be there. The mock server will ignore addiotional elements.

**Comment by sanketi** [comment]
Hi @uglyog, 
If I send additional elements not defined in Pact Fragment, then I get this error - 
au.com.dius.pact.consumer.PactMismatchException: Pact verification failed for the following reasons:
    BodyMismatch - Expected a Map with 3 elements but received 4 elements

the documentation here http://docs.pact.io/documentation/gotchas.html it says -
"Be conservative in what you send - when the mock server in the consumer project compares the actual request with the expected request, the actual request body is not allowed to contain fields that are not defined in the expected request body. We don't want the situation where our real consumer is "leaking" data that we don't know about."

Am I doing something incorrect here? 
Thank you for assistance.

**Comment by uglyog** [comment]
Sorry, my mistake, that is the correct rule in the documentation. 

If they are optional, could you get your client code to not include them?

**Comment by uglyog** [comment]
I'm thinking of adding an ignored matcher to support this.

**Comment by sanketi** [comment]
that would be very helpful. Thank you.

**Comment by arther** [comment]
Hi @uglyog 
> I'm thinking of adding an ignored matcher to support this.

Is this feature available to use or would you suggest any other way to achieve it.

**Comment by uglyog** [comment]
@arther, currently there is no support for something like this. The normal way to do it is to have a contract test for the different options that are important.

**Comment by arther** [comment]
@uglyog Thanks for the quick reply 👍

**Comment by uglyog** [comment]
Closing this as the recommended way is to have different tests for the different options and use provider states.

**Comment by mforsmanpaypal** [comment]
In my organisation we use common request bodies containing various fields for analytics, metadata and such, and then we append these base requests with additional endpoint-specific data as well. A lot of the common fields are just ignored if they are not needed by the endpoint in question.

Example:

```
{
  "baseMetaData": "i dont matter",                    //common field present in every request
  "importantContractData": "witness me"        //specific to the endpoint I am currently testing
}
```

I would like to define a contract that requires only `importantContractData` to be present, but allows additional unspecified fields. However, this seems to not be possible in Pact. This means that we cannot practically use it, since it is impossible to keep up with the frequently changing common fields, and it is also impractical to specify 20+ irrelevant metadata fields for each contract test.

As per this comment:

> the actual request body is not allowed to contain fields that are not defined in the expected request body. We don't want the situation where our real consumer is "leaking" data that we don't know about.

I understand the authors feel that submitting superfluous fields in a request body is bad practice, but without getting into that discussion I feel that imposing such a limitation on the tool to in order to encourage a different style of API design is perhaps not the place for a testing framework. If we want to leak data I feel like this should be our prerogative, and it would be quite nice to allow for "extra" fields in Pact to enable testing for our use-case.

Any thoughts on this?

**Comment by rholshausen** [comment]
@mforsmanpaypal can you raise a separate issue for that? You can just copy the contents of the comment.
