### ISSUE TITLE
Reduce maven transient dependecie

### ISSUE THREAD

**Issue by Thadir** [pact-foundation/pact-jvm#439]
The dependency list of the pact-jvm-provider and consumer for junit, are a bit big. And can cause a lot of conflicts (think about the sl4j dependence thats cross project from pact-jvm-model to pact-jvm-matcher etc).

We should analyse and reduce the needed packages (and if possible reduce the amount of nested dependencies (but this could be a scala thin).

**Comment by tmszdmsk** [comment]
I researched topic of CDC today and, to be honest, I am not sure if I should use pact-jvm because of all of these dependencies. scala, kotlin, groovy, aws sdk, gson, kotson, jackson, jsonpath, netty, etc.

I had to exclude some libs in `build.gradle` dependencies of pact-jvm because they clashed with project ones.

* Do you plan to eradicate kotlin, scala and groovy from dependencies?
* Did you thought about distributing pact-jvm as shadow jars (aka fat jars)

------------------------
* [list of dependencies for consumer test](https://gist.github.com/tmszdmsk/edb99e342c9133babbbb4fae2db5d749#file-pact-jvm-consumer-dependencies-txt)
* [list of dependencies for provider test](https://gist.github.com/tmszdmsk/edb99e342c9133babbbb4fae2db5d749#file-pact-jvm-provider-dependencies-txt)

**Comment by uglyog** [comment]
There is no plan to eradicate Kotlin, the plan is to replace Scala with Kotlin.

**Comment by tmszdmsk** [comment]
Do you need help on that? What module can I start with?

**Comment by uglyog** [comment]
@tmszdmsk pact-jvm-matchers is a core component that is used by everything else, so converting that would be the place to start.

The other one is converting the Groovy code in pact-jvm-model.
